# Exercises: Floating-point numbers and NumPy

This notebook accompanies:

- `01_Floating_point_numbers.ipynb`
- `02_Numpy_basics.ipynb`

## How to work

1. Write your own code in the empty code cell below each task.
2. Try the task for a few minutes before opening the hint.
3. Reveal the full solution only after you have written an attempt.
4. Type the solution yourself rather than copying it.
5. Use descriptive variable names and make sure you understand every line.
6. When you finish, restart the kernel and run the notebook from top to bottom.

The exercises are independent. Getting stuck on one exercise does not prevent you from starting the next one.

The examples use small numerical calculations. No additional economics knowledge is needed.

The hints and solutions are collapsed. Click the small triangle to reveal them.

## 1. Comparing computed decimal numbers

Computers cannot represent every decimal number exactly. In this exercise, you will see why exact equality can be misleading.

1. Set `total = 0.0`.
2. Use a `for` loop to add `0.1` to `total` ten times.
3. Print `total`.
4. Check whether `total == 1.0` and print the result.
5. Import `math` and use `math.isclose` to compare `total` with `1.0`.
6. Print the small difference `total - 1.0`.

Before running the code, predict whether the two comparisons will give the same answer.

In [ ]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

Begin with:

```python
total = 0.0

for repetition in range(10):
    total = total + 0.1
```

Use `math.isclose(total, 1.0)` for the comparison with a tolerance.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
import math

total = 0.0

for repetition in range(10):
    total = total + 0.1

print('total =', total)
print('exactly equal to 1.0 =', total == 1.0)
print('close to 1.0 =', math.isclose(total, 1.0))
print('difference =', total - 1.0)
```

The result is close to:

```python
total = 0.9999999999999999
exactly equal to 1.0 = False
close to 1.0 = True
difference = -1.1102230246251565e-16
```

The small difference comes from the finite representation of decimal numbers. For computed floating-point numbers, use a comparison with a tolerance rather than `==`.

</details>

## 2. Prices and quantities as NumPy arrays

A household buys four goods. Prices and quantities are stored in NumPy arrays.

1. Print the type, shape, size and data type of `prices`.
2. Calculate expenditure on each good without using a loop:

$$
\text{item expenditure} = \text{price} \cdot \text{quantity}.
$$

3. Store the result as `item_expenditures` and print it.
4. Calculate and print total expenditure with `np.sum`.
5. Calculate and print mean expenditure per good with `np.mean`.
6. Print the expenditure on the first and last goods using indexing.
7. Create `higher_prices` by increasing every price by 5 percent.
8. Calculate total expenditure with the higher prices and print the change in total expenditure.

In [ ]:
import numpy as np

prices = np.array([18.0, 12.0, 30.0, 8.0])
quantities = np.array([2.0, 3.0, 1.0, 5.0])

In [ ]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

NumPy applies arithmetic element by element:

```python
item_expenditures = prices * quantities
```

A 5 percent price increase can be written as:

```python
higher_prices = 1.05 * prices
```

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
print('type =', type(prices))
print('shape =', prices.shape)
print('size =', prices.size)
print('data type =', prices.dtype)

item_expenditures = prices * quantities

print('item expenditures =', item_expenditures)
print('total expenditure =', np.sum(item_expenditures))
print('mean expenditure =', np.mean(item_expenditures))
print('first expenditure =', item_expenditures[0])
print('last expenditure =', item_expenditures[-1])

higher_prices = 1.05 * prices
higher_item_expenditures = higher_prices * quantities
higher_total_expenditure = np.sum(higher_item_expenditures)

print('higher prices =', higher_prices)
print('higher total expenditure =', higher_total_expenditure)
print('change in total expenditure =',
      higher_total_expenditure - np.sum(item_expenditures))
```

The item expenditures are:

```python
[36. 36. 30. 40.]
```

Total expenditure is 142 DKK. With prices 5 percent higher, total expenditure is approximately 149.1 DKK.

</details>

## 3. Keep a baseline and a scenario separate

You want to compare baseline prices with a scenario in which the first two prices are 10 percent higher.

The baseline array must remain unchanged.

1. Create `scenario_prices` as an independent copy of `baseline_prices`.
2. Use a slice to increase the first two elements of `scenario_prices` by 10 percent.
3. Print both price arrays and confirm that `baseline_prices` did not change.
4. Calculate total expenditure under the baseline prices.
5. Calculate total expenditure under the scenario prices.
6. Print both totals and their difference.

Do not create the scenario with `scenario_prices = baseline_prices[:]`. A slice of a NumPy array is a view, not an independent copy.

In [ ]:
import numpy as np

baseline_prices = np.array([20.0, 35.0, 12.0, 8.0])
quantities = np.array([2.0, 1.0, 4.0, 3.0])

In [ ]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

Create the independent array with:

```python
scenario_prices = baseline_prices.copy()
```

The first two elements are selected with:

```python
scenario_prices[0:2]
```

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
scenario_prices = baseline_prices.copy()
scenario_prices[0:2] = 1.10 * scenario_prices[0:2]

print('baseline prices =', baseline_prices)
print('scenario prices =', scenario_prices)

baseline_expenditures = baseline_prices * quantities
scenario_expenditures = scenario_prices * quantities

baseline_total = np.sum(baseline_expenditures)
scenario_total = np.sum(scenario_expenditures)

print('baseline total =', baseline_total)
print('scenario total =', scenario_total)
print('difference =', scenario_total - baseline_total)
```

The baseline array remains:

```python
[20. 35. 12.  8.]
```

The scenario array is:

```python
[22.  38.5 12.   8. ]
```

Baseline expenditure is 147 DKK and scenario expenditure is 154.5 DKK.

The `.copy()` is necessary because changing a view would also change the original array.

</details>

## 4. Select observations with logical indexing

The array below contains illustrative monthly incomes in DKK.

1. Calculate and print the mean income.
2. Create a boolean array called `above_mean` that is `True` when income is above the mean.
3. Use the boolean array to create `incomes_above_mean`.
4. Print the boolean array and the selected incomes.
5. Calculate the number of incomes above the mean using `.size`.
6. Calculate their share of all observations.
7. Create a second boolean array called `between_20_and_30` that selects incomes from 20,000 DKK to 30,000 DKK, including both limits.
8. Print the incomes selected by the second condition.

Use `&` to combine the two conditions in step 7.

In [ ]:
import numpy as np

monthly_incomes = np.array([
    18_000.0,
    24_000.0,
    32_000.0,
    15_000.0,
    41_000.0,
    26_000.0
])

In [ ]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

Logical indexing follows this pattern:

```python
condition = monthly_incomes > some_value
selected_values = monthly_incomes[condition]
```

Combine two array conditions with parentheses and `&`:

```python
(first_condition) & (second_condition)
```

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
mean_income = np.mean(monthly_incomes)

above_mean = monthly_incomes > mean_income
incomes_above_mean = monthly_incomes[above_mean]

number_above_mean = incomes_above_mean.size
share_above_mean = number_above_mean / monthly_incomes.size

between_20_and_30 = (
    (monthly_incomes >= 20_000) &
    (monthly_incomes <= 30_000)
)
incomes_between_20_and_30 = monthly_incomes[between_20_and_30]

print('mean income =', mean_income)
print('above mean =', above_mean)
print('incomes above mean =', incomes_above_mean)
print('number above mean =', number_above_mean)
print('share above mean =', share_above_mean)
print('incomes from 20,000 to 30,000 =',
      incomes_between_20_and_30)
```

The mean is 26,000 DKK. The incomes strictly above the mean are 32,000 DKK and 41,000 DKK. Their share is one third.

The incomes between 20,000 DKK and 30,000 DKK are 24,000 DKK and 26,000 DKK.

</details>

## 5. Optional: a two-dimensional sales table

A shop sells two products over three months.

- Each row in `quantities_sold` is a month.
- Each column is a product.
- `prices` contains one price for each product.

1. Print the shape of both arrays.
2. Calculate revenue for every month and product with `quantities_sold * prices`.
3. Explain to yourself why broadcasting works for arrays with shapes `(3, 2)` and `(2,)`.
4. Calculate total revenue in each month with `np.sum(..., axis=1)`.
5. Calculate total revenue for each product with `np.sum(..., axis=0)`.
6. Calculate overall revenue.
7. Use `math.isclose` to check that the sum of monthly revenue equals overall revenue.

In [ ]:
import math
import numpy as np

quantities_sold = np.array([
    [10.0, 5.0],
    [12.0, 4.0],
    [9.0, 7.0]
])

prices = np.array([25.0, 40.0])

In [ ]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

The one-dimensional price array matches the two columns of the quantities array:

```python
revenue = quantities_sold * prices
```

For this table:

- `axis=0` reduces the rows and leaves one value per column,
- `axis=1` reduces the columns and leaves one value per row.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
print('quantities shape =', quantities_sold.shape)
print('prices shape =', prices.shape)

revenue = quantities_sold * prices

monthly_revenue = np.sum(revenue, axis=1)
product_revenue = np.sum(revenue, axis=0)
total_revenue = np.sum(revenue)

print('revenue table =')
print(revenue)
print('monthly revenue =', monthly_revenue)
print('product revenue =', product_revenue)
print('total revenue =', total_revenue)
print('totals agree =',
      math.isclose(np.sum(monthly_revenue), total_revenue))
```

The revenue table is:

```python
[[250. 200.]
 [300. 160.]
 [225. 280.]]
```

Monthly revenue is `[450., 460., 505.]`. Revenue by product is `[775., 640.]`. Overall revenue is 1,415 DKK.

</details>

## Final check

Before you finish:

1. Save the notebook.
2. Restart the kernel.
3. Run all cells from top to bottom.
4. Confirm that there are no error messages.
5. Be able to explain:
   - why exact equality is unreliable for computed floating-point numbers,
   - how NumPy applies arithmetic element by element,
   - why `.copy()` is sometimes necessary,
   - how a boolean array selects observations,
   - what `axis=0` and `axis=1` do in a two-dimensional array.