# Numpy basics

**Table of contents**<a id='toc0_'></a>    
- 1. [Basics](#toc1_)    
- 2. [Math](#toc2_)    
- 3. [Broadcasting](#toc3_)    
- 4. [Indexing](#toc4_)    
- 5. [Arrays with more than two dimensions](#toc5_)    
- 6. [List of good things to know](#toc6_)    
- 7. [Small quiz](#toc7_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

**[Numpy](https://numpy.org/)** is the main package for handling numerical data

In [2]:
import numpy as np # import the numpy module

A **numpy array** is a lot like a list but with important differences:

1. Elements are typically **one homogenous type** (ints, floats...).
2. A **slice returns a view** rather than a copy of the content.

Thus, numpy arrays are less flexible than lists.

But that is what allows them to use more **efficient mathematical** routines.

**Further:** [Very detailed numpy tutorial](https://www.python-course.eu/numpy.php).

## 1. <a id='toc1_'></a>[Basics](#toc0_)

Numpy arrays can be **created from lists** and can be **multi-dimensional**:

In [7]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # one dimension
B = np.array([[3.4, 8.7, 9.9], 
              [1.1, -7.8, -0.7],
              [1. , 0.5 , -5.7],
              [4.1, 12.3, 4.8]]) # two dimensions

print('A is a', type(A),'and B is a', type(B)) # type
print('As data is',A.dtype,'Bs data is' , B.dtype) # data type
print('A dimensions:', A.ndim, 'B dimensions:',B.ndim) # dimensions
print('shape of A:',A.shape,'shape of B:',B.shape) # shape (1d: (columns,), 2d: (row,columns))
print('size of A:',A.size,'size of B:',B.size) # size

A is a <class 'numpy.ndarray'> and B is a <class 'numpy.ndarray'>
As data is int64 Bs data is float64
A dimensions: 1 B dimensions: 2
shape of A: (10,) shape of B: (4, 3)
size of A: 10 size of B: 12


Notice that the matrix `B` was a bunch of stacked **rows**.

Python is a row major language which means the elements of the ndarray are stored in memory as concatenated rows (Fortran, MATLAB, and Julia are examples of column major languages).

**Slicing** a numpy array returns a **view**, which is a **reference** to the part of the array that was sliced out.

*Remember that views and copies can be extracted from containers.* <br> 
*Views allow for changing the original object when the view is changed; copies do not.*

In [8]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
V = A[2:6]         # V is a reference to a slice of a A

# Make changes in V and note what happens in A
V[0] = 0; V[1] = 0  # The ; allows you to write multiple code-lines in a single line
print('V =',V)
print('A =',A,'changed')     # A has changed

# If C was a copy, A wouldn't have changed
C = A.copy()
C[0] = 99
print('A =',A, 'did not change') 

V = [0 0 4 5]
A = [0 1 0 0 4 5 6 7 8 9] changed
A = [0 1 0 0 4 5 6 7 8 9] did not change


Numpy array can also be created using numpy functions:

In [4]:
print(np.ones((2,3)))
print(np.zeros((4,2)))
print(np.eye(2,))
print(np.linspace(0,1,6))   # linear spacing between endpoints
print(np.arange(0, 10, 2))  # start, stop, step (like Python's range)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[0.  0.2 0.4 0.6 0.8 1. ]
[0 2 4 6 8]


**Tip 1:** Try typing `np.linspace(`

**Tip 2:** Try to write `?np.linspace` in a cell

In [ ]:
?np.linspace

## 2. <a id='toc2_'></a>[Math](#toc0_)

Numpy arrays are designed for **mathematical operations**

Operations * + - / happen element-by-element between to ndarrays.

In [ ]:
A = np.array([[1,0],[0,1]])
B = np.array([[2,2],[2,2]])

print('A\n',A,'\nB\n',B)
print('A+B\n',A+B,'\n') # Add 2 numpy arrays element-by-element

In [ ]:
# More examples
print('A-B\n',A-B,'\n')
print('A*B\n',A*B,'\n') # element-by-element product
print('A/B\n',A/B,'\n') # element-by-element division
print('A@B\n',A@B,'\n') # matrix product

NumPy also provides **universal functions** (ufuncs) that apply element-wise to entire arrays — essential for evaluating economic functions over grids without writing a loop:

In [ ]:
x = np.linspace(1, 5, 5)
print(np.log(x))    # natural log
print(np.exp(x))    # exponential
print(np.sqrt(x))   # square root

Evaluate a Cobb-Douglas utility function over a grid — no loop needed:

In [ ]:

x1 = np.linspace(0.1, 10, 5)
x2 = 4.0
alpha = 0.5
utility = x1**alpha * x2**(1-alpha)
print('utility:', utility.round(2))

## 3. <a id='toc3_'></a>[Broadcasting](#toc0_)


**Motivation:** Often you want to combine arrays of *different shapes*. For example, to evaluate a utility function for every combination of a vector of $x_1$ values and a vector of $x_2$ values. Instead of writing nested loops, **broadcasting** lets numpy stretch the smaller array across the larger one automatically — shorter to write and much faster to run.

* If arrays **do not** fit together **broadcasting** is applied.  
* When broadcasting, numpy uses the dimensions that **do fit** (if possible).  
* **Simple case:** multiplying a scalar (an array with 1 element) with a larger ndarray.

In [ ]:
A = np.array([[10, 20, 30], 
              [40, 50, 60]]) # shape = (2,3) 
              
B = np.array([1, 2, 3]) # shape = (3,) = (1,3)

print('A\n',A, A.shape)
print('B\n',B, B.shape) # Notice the shape 'transformation' column vector!
print('\nMultiplication along columns')
print(A*B) 

Another example. Note that B above did not have a 2nd dimension.  
C has **explicitly** 2 rows and 1 column when created as such.

In [ ]:
C = np.array([[1],[2]]) 

print(C, C.shape, '\n') 
print(A*C,'\n') # each row is scaled by the corresponding element of C

If you want to e.g. add arrays where broadcasting is not possible, you can **explicitly** specify a new axis with `None`.

In [ ]:
A = np.array([1, 2, 3]) # Is only 1D, shape = (3,)
B = np.array([1,2]) # Is only 1D, shape = (2,)

# You cannot broadcast B on A, because neither have 2 dimensions.
# Therefore, use newaxis
print(A[:,None], A[:,None].shape, '\n') # Is now (3,1)
print(B[None,:], B[None,:].shape, '\n') # Is now (1,2)

print(A[:,None]*B[None,:], '\n') # A is column vector, B is row vector
print(A[None,:]*B[:,None]) # A is row vector, B is column vector

**More on broadcasting:** [Documentation](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).

A lot of **mathematical procedures** can easily be performed on numpy arrays.

Many functions accept an **`axis`** argument for reducing along rows or columns of a 2D array:

In [ ]:
A =  np.array([3.1, 2.3, 9.1, -2.5, 12.1])
print(np.min(A)) # find minimum
print(np.argmin(A)) # find index for minimum
print(np.mean(A)) # calculate mean
print(np.sort(A)) # sort (ascending)

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(M))            # total sum: 21
print(np.sum(M, axis=0))    # sum along rows → column sums: [5, 7, 9]
print(np.sum(M, axis=1))    # sum along columns → row sums: [6, 15]
print(np.mean(M, axis=0))   # column means

**Note:** Sometimes a method can be used instead of a function, e.g. ``A.mean()``. 

In numpy all methods are available as functions but not all functions are available as methods. Sometimes there are minute differences between them, like whether they return a copy or a view.

We'll tend to stick to functions.

## 4. <a id='toc4_'></a>[Indexing](#toc0_)

**Multi-dimensional** indexing is done as:

In [ ]:
X = np.array([ [11, 12, 13], 
               [21, 22, 23] ])
print('X\n',X)
print('\nX[0]\n',X[0]) # first row, all columns (this is implicitly X[0,:])
print('\nX[:,0]\n',X[:,0]) # all rows, first column
print('\nX[1,2]\n',X[1,2]) # second row, third column
print('\nX[0:2,1:3]\n',X[0:2,1:3]) # rows 1-2, Column 2-3

Indexes can be **logical**. Logical 'and' is `&` and logical 'or' is `|`.

In [ ]:
A = np.array([1,2,3,4,1,2,3,4])
B = np.array([3,3,3,3,2,3,2,2])
I = (A < 3) & (B == 3) # note & instead of 'and', indicates element-wise comparison
print(I)
print(A[I],'\n')

# Two ways of getting indices of the elements == True
print(np.where(I)) # A 'where' clause normally asks for where the True elements are.
print(np.nonzero(I)) # Because a True boolean is a 1 while a False is a 0.

In [ ]:
I = (A < 3) | (B == 3) # note | instead of 'or'
print(A[I])

## 5. <a id='toc5_'></a>[Arrays with more than two dimensions](#toc0_)

Arrays can have more dimensions than two — they become more difficult to understand but can be really useful. <br>
The Python way of thinking about them is as matrices storing matrices. <br>
In the shape attribute, the rows and columns of the **innermost** matrix are the last two elements of the shape.

In [ ]:
A_i = np.array([[1,2],
                [3,4]])

A = np.array([A_i,A_i,A_i])

print(A.shape) # (Number of matrices,rows,cols)
print()
print(A)

In [ ]:
B_i = np.array([[5,5],
                [5,5]])

AB = np.array([[A_i,A_i,A_i],
                [B_i,B_i,B_i]])

print(AB.shape) # (rows in matrix of matrices , columns in matrix of matrices, rows, columns )
print()
print(AB)

**Note:** the inner matrices (A_i and B_i) should be of the same shape

## 6. <a id='toc6_'></a>[List of good things to know](#toc0_)

**Attributes and methods** to know:

- size / ndim / shape
- ravel / reshape / sort
- copy

**Functions** to know:

- array / empty / zeros / ones / linspace / arange
- mean / median / std / var / sum / percentile
- min/max, argmin/argmax / fmin / fmax / sort / clip
- meshgrid / hstack / vstack / concatenate / tile / insert
- allclose / isnan / isinf / isfinite / any / all

**Concepts** to know:

- view vs. copy
- broadcasting
- logical indexing

The important thing is not to try to memorize all of this.

The important thing is to understand the logic of how numpy works and get an idea about the things numpy can help you with.

Googling numpy and what mathematical operation you want to do will more often than not give a numpy function that does what you're looking for.

As you code during your projects, you'll naturally memorize the functionalities you find most useful.

## 7. <a id='toc7_'></a>[Small quiz](#toc0_)

What follows is a number of codeblocks, with print statements that are commented out. Try to predict what will be printed, and check if you're correct afterwards.

import numpy as np
np.array(b) = [True,True,True,True]


In [ ]:
import numpy as np
b = [True,True,False,True]
c = [7,8,9,10]
b = np.array(b)
c = np.array(c)
e = c[b]
print(e)

[ 7  8 10]


In [21]:
A = np.array([1, 2, 3, 4])
B = np.array([3,3,2,2])
I = (B==3) | (A>=1)
print(B[I])
A = np.array([1, 2, 3, 4])
A = A[:,None]
print(A)
type(A)

[3 3 2 2]
[[1]
 [2]
 [3]
 [4]]


numpy.ndarray

In [ ]:
A = np.ones((4,2))*2
B = A[0:2,1]+ 1 
# printer 2 i de første tre rækker i anden kolonne.
print(B)

[3. 3.]


In [25]:
A = np.ones((4,2))*2
B = A[0:2,1]+ 1 
#printer [3., 3.]
print(B)

[3. 3.]


In [ ]:
A = np.ones((2,2))
B = np.array([[5],[10]])
# printer True
print(np.all(A*B==B*A))

True


In [27]:
A = np.array([1,2,3,4,5])
B = A[3:] # udvælger [4,5]
B[:] = 0 # da B er et view sættes 4 og 5 i b til 0.
print(np.sum(A))

6
